version: '3.8'

services:
  airi_personality:
    build:
      context: ./airi_personality
    ports:
      - "5001:5001"
    depends_on:
      - ollama
    networks:
      - airi_network

  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    networks:
      - airi_network

  voice_svc:
    build:
      context: ./voice_svc
    ports:
      - "5000:5000"
    depends_on:
      - airi_personality
    networks:
      - airi_network

  # esp32_nmcu:
  #   build:
  #     context: ./esp32_nmcu
  #   networks:
  #     - airi_network
